### ISSUE TITLE
IPS 4.4 Compatible?

### ISSUE THREAD

**Issue by STX2k** [DanielFatkic/rollbar#4]
Hey if i want to install your Plugin i get an Error. 

`1C133/K The application you uploaded cannot be installed because it is not a valid application, the archive is corrupt or the file and directory permissions in /applications do not allow it.`

is it compatible to IPS 4.4?

**Comment by DanielFatkic** [comment]
Yes, it's compatible with 4.4.x
I'm using it on several communities.

**Comment by STX2k** [comment]
Mhhh okay. But if i download your tar.gz or zip it doesnt work. Also if i repack it to a .tar archive.

**Comment by STX2k** [comment]
*push*
